### ISSUE TITLE
Cannot build with GHC 8.4.3

### ISSUE THREAD

**Issue by samblackmore** [rodrigosetti/swagger-test#5]
Would love to try this but I can't build the repo! Running `cabal install` or `cabal build` gives...

```
Preprocessing library for swagger-test-0.2.7..
Building library for swagger-test-0.2.7..
[5 of 8] Compiling Test.Swagger.Gen ( src/Test/Swagger/Gen.hs, dist/build/Test/Swagger/Gen.o )

src/Test/Swagger/Gen.hs:305:29: error:
    • Couldn't match type ‘AdditionalProperties’
                     with ‘Referenced Schema’
        arising from a functional dependency between:
          constraint ‘HasAdditionalProperties
                        Schema (Maybe (Referenced Schema))’
            arising from a use of ‘additionalProperties’
          instance ‘HasAdditionalProperties
                      Schema (Maybe AdditionalProperties)’
            at <no location info>
    • In the second argument of ‘(^.)’, namely ‘additionalProperties’
      In the expression: s ^. additionalProperties
      In a stmt of a 'do' block:
        addPropsV <- case s ^. additionalProperties of
                       Just (Inline s')
                         -> replicateM (nProps - (nOptProps + length reqProps))
                              $ do k <- genNonemptyText
                                   (k,) <$> genJSON s'
                       _ -> pure []
    |
305 |      addPropsV <- case s ^. additionalProperties of
    |                             ^^^^^^^^^^^^^^^^^^^^
[6 of 8] Compiling Test.Swagger.Validate ( src/Test/Swagger/Validate.hs, dist/build/Test/Swagger/Validate.o )
```

**Comment by rodrigosetti** [comment]
Please use [haskell stack](https://docs.haskellstack.org/) to build. It is much more reproducible than cabal, and it works with the latest [LTS 12.17](https://www.stackage.org/lts-12.17) with GHC 8.4.4
